# Railway Configuration
# This file tells Railway how to deploy your backend

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python -m uvicorn simple_main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
# Set these in Railway dashboard
SEARCHAPI_KEY = "your_yahoo_search_api_key_here"
PYTHON_VERSION = "3.11"
